# Site settings
title: Clever Blog Title. Lol.
email: matthew@wetheplural.com
description: > # this means to ignore newlines until "baseurl:"
  iOS developer, wannabe Rubyist, recovering mathematician.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sweetverbs.github.io" # the base hostname & protocol for your site
twitter_username: meanestcreature
github_username:  sweetverbs

# Build settings
markdown: kramdown
